apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: mycustomresources.demo.ubertob.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: demo.ubertob.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                containerName:
                  type: string
                containerImage:
                  type: string
                replicas:
                  type: integer
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: MyCustomResource
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: mycustomresources
    # singular name to be used as an alias on the CLI and for display
    singular: mycustomresource
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - mcr
